import type { AgeGroup, QualitySetting } from '@/types';
import type { G } from './gender';

/** All player-facing interface text. Hebrew only — no strings live inside components. */
export const UI = {
  title: 'מבוך החידות',
  subtitle: 'ידע הוא המפתח. הזמן הוא האויב.',
  menu: {
    start: 'התחל משחק',
    howTo: 'איך משחקים',
    leaderboard: 'טבלת המובילים',
    settings: 'הגדרות',
    footer: 'כל משחק — מבוך חדש, יצורים חדשים וחידות חדשות',
  },
  common: {
    back: 'חזרה',
    continue: 'המשך',
    close: 'סגירה',
    yes: 'כן',
    no: 'לא',
    loading: 'טוען…',
    seconds: 'שניות',
    minutes: 'דקות',
  },
  age: {
    title: 'בחירת קבוצת גיל',
    prompt: 'הגיל קובע את רמת החידות ואת גודל המבוך.',
    groups: {
      '5-7': { label: '5–7', name: 'גילאי', hint: 'מבוך קטן וחידות ראשונות' },
      '8-10': { label: '8–10', name: 'גילאי', hint: 'מבוך בינוני וחידות סקרנות' },
      '11-13': { label: '11–13', name: 'גילאי', hint: 'מבוך מסועף וחידות מאתגרות' },
      '14-15': { label: '14–15', name: 'גילאי', hint: 'מבוך גדול וחידות קשות' },
      '16+': { label: '16+', name: 'גילאי', hint: 'מבוך ענק וחידות למביני עניין' },
    } satisfies Record<AgeGroup, { label: string; name: string; hint: string }>,
  },
  setup: {
    title: 'מי נכנס למבוך?',
    addressLabel: 'איך לפנות אליך?',
    addressM: 'בלשון זכר',
    addressF: 'בלשון נקבה',
    nicknameLabel: 'כינוי (לא חובה)',
    nicknamePlaceholder: 'למשל: אביר הלילה',
    nicknameHint: 'הכינוי יופיע בטבלת המובילים. אין צורך בשם אמיתי.',
    enter: { m: 'היכנס למבוך', f: 'היכנסי למבוך' } as G,
    tutorialFirst: { m: 'הצג לי הדרכה קצרה', f: 'הציגי לי הדרכה קצרה' } as G,
    skipTutorial: 'דילוג על ההדרכה',
    errors: {
      tooShort: 'הכינוי צריך להכיל לפחות 2 תווים.',
      tooLong: 'הכינוי יכול להכיל עד 16 תווים.',
      invalid: 'אפשר להשתמש באותיות, ספרות ורווחים בלבד.',
      inappropriate: { m: 'הכינוי הזה אינו מתאים. נסה כינוי אחר.', f: 'הכינוי הזה אינו מתאים. נסי כינוי אחר.' } as G,
    },
    anonymous: 'הרפתקן אלמוני',
  },
  loading: {
    building: 'המבוך נבנה…',
    steps: ['חוצבים מסדרונות', 'מדליקים לפידים', 'מעירים את היצורים', 'מסתירים אוצרות'],
    enteringTheme: 'נכנסים אל',
  },
  hud: {
    time: 'זמן',
    lives: 'חיים',
    treasures: 'אוצרות',
    score: 'ניקוד',
    map: 'מפה',
    pause: 'השהיה',
    checkpoint: 'נקודת ביקורת',
    clickToPlay: { m: 'לחץ על המסך כדי להמשיך לשחק', f: 'לחצי על המסך כדי להמשיך לשחק' } as G,
    tapToPlay: { m: 'גע במסך כדי להמשיך', f: 'געי במסך כדי להמשיך' } as G,
    livesAria: 'חיים שנותרו: {n}',
    timeAria: 'זמן שנותר: {t}',
  },
  coach: {
    moveDesktop: { m: 'השתמש במקשים ⁦W A S D⁩ כדי ללכת', f: 'השתמשי במקשים ⁦W A S D⁩ כדי ללכת' } as G,
    lookDesktop: { m: 'הזז את העכבר כדי להסתכל סביב', f: 'הזיזי את העכבר כדי להסתכל סביב' } as G,
    moveTouch: { m: 'גרור את הג׳ויסטיק השמאלי כדי ללכת', f: 'גררי את הג׳ויסטיק השמאלי כדי ללכת' } as G,
    lookTouch: { m: 'גרור בצד ימין של המסך כדי להסתכל', f: 'גררי בצד ימין של המסך כדי להסתכל' } as G,
    sprint: { m: 'החזק ⁦Shift⁩ כדי ללכת מהר יותר', f: 'החזיקי ⁦Shift⁩ כדי ללכת מהר יותר' } as G,
    explore: { m: 'חפש יצורים בצמתים — הם יודעים את הדרך', f: 'חפשי יצורים בצמתים — הם יודעים את הדרך' } as G,
    creatureAhead: { m: 'יצור מחכה לך בצומת. התקרב אליו.', f: 'יצור מחכה לך בצומת. התקרבי אליו.' } as G,
    followLight: { m: 'עקוב אחרי האור — זו הדרך שהיצור גילה לך', f: 'עקבי אחרי האור — זו הדרך שהיצור גילה לך' } as G,
    ownWay: { m: 'הפעם תצטרך למצוא את הדרך בעצמך. כל הדרכים פתוחות.', f: 'הפעם תצטרכי למצוא את הדרך בעצמך. כל הדרכים פתוחות.' } as G,
    map: { m: 'לחץ ⁦M⁩ כדי לפתוח את המפה הקסומה', f: 'לחצי ⁦M⁩ כדי לפתוח את המפה הקסומה' } as G,
  },
  encounter: {
    chooseAnswer: { m: 'בחר תשובה', f: 'בחרי תשובה' } as G,
    keyboardHint: 'מקשים ⁦1–4⁩',
    correct: 'תשובה נכונה!',
    wrong: 'לא הפעם…',
    correctAnswerWas: 'התשובה הנכונה:',
    points: '+{n} נקודות',
    penalty: '−{n} נקודות',
    continue: { m: 'המשך בדרך', f: 'המשיכי בדרך' } as G,
    letters: ['א', 'ב', 'ג', 'ד'],
    difficulty: { easy: 'קלה', medium: 'בינונית', hard: 'קשה', expert: 'קשה מאוד' },
    category: 'נושא',
    callOut: 'הֵי! כאן, לידך!',
  },
  route: {
    ahead: 'הדרך הנכונה לפניך',
    right: 'הדרך הנכונה מימינך',
    left: 'הדרך הנכונה משמאלך',
    behind: 'הדרך הנכונה מאחוריך',
  },
  special: {
    accept: { m: 'אני מסכים', f: 'אני מסכימה' } as G,
    decline: 'לא, תודה',
    oracleCost: 'מחיר: 100 נקודות',
    merchantCost: 'מחיר: 2 אוצרות',
    notEnough: { m: 'אין לך מספיק אוצרות. חזור כשתמצא עוד.', f: 'אין לך מספיק אוצרות. חזרי כשתמצאי עוד.' } as G,
    oracleDone: 'המפה הקסומה מתבהרת…',
    merchantDone: 'החול בשעון זורם לאחור — קיבלת דקה נוספת!',
  },
  toast: {
    checkpoint: 'נקודת ביקורת נשמרה',
    treasure: 'נמצא אוצר: {name}',
    treasureBanked: 'האוצרות שלך מוגנים',
    tension: 'נותרו פחות משתי דקות!',
    urgent: 'פחות מחצי דקה!',
    exitSeen: 'ראית את היציאה!',
    mapRevealed: 'חלק מהמבוך נגלה במפה',
  },
  pause: {
    title: 'המשחק מושהה',
    resume: 'המשך לשחק',
    settings: 'הגדרות',
    howTo: 'איך משחקים',
    quit: 'יציאה לתפריט',
    quitConfirm: { m: 'לצאת מהמשחק? ההתקדמות במבוך הזה תאבד.', f: 'לצאת מהמשחק? ההתקדמות במבוך הזה תאבד.' } as G,
    quitYes: 'כן, לצאת',
    quitNo: 'הישארות במבוך',
  },
  lifeLost: {
    title: 'המבוך החזיר אותך לאחור',
    subtitle: 'הזמן אזל, והקירות נסגרו סביבך…',
    remaining: 'נותרו {n} חיים',
    remainingOne: 'נותרו חיים אחרונים',
    treasuresLost: 'אוצרות שלא נשמרו חזרו אל המבוך',
    returning: 'חוזרים לנקודת הביקורת האחרונה…',
  },
  gameOver: {
    title: { m: 'נפסלת', f: 'נפסלת' } as G,
    subtitle: 'המבוך שמר על סודותיו — הפעם.',
    retry: 'נסה שוב',
    menu: 'חזרה לתפריט',
    leaderboard: 'טבלת המובילים',
  },
  victory: {
    title: 'המבוך הושלם!',
    subtitle: { m: 'יצאת אל האור — חכם, אמיץ ומהיר.', f: 'יצאת אל האור — חכמה, אמיצה ומהירה.' } as G,
  },
  summary: {
    title: 'סיכום המסע',
    questionsAnswered: 'חידות שנענו',
    correct: 'תשובות נכונות',
    wrong: 'תשובות שגויות',
    timeSurvived: 'זמן במבוך',
    livesLost: 'חיים שאבדו',
    treasuresFound: 'אוצרות',
    breakdown: {
      trivia: 'ניקוד חידות',
      timeBonus: 'בונוס זמן',
      livesBonus: 'בונוס חיים',
      treasures: 'אוצרות',
      efficiency: 'בונוס דרך יעילה',
      penalties: 'קנסות',
      total: 'ניקוד סופי',
    },
    submit: 'שמירה בטבלת המובילים',
    submitting: 'שומר…',
    submitted: 'התוצאה נשמרה!',
    submitFailed: 'השמירה נכשלה. ננסה שוב בעוד רגע.',
    submitRejected: 'לא ניתן לשמור את התוצאה הזו.',
    playAgain: 'משחק חדש',
    menu: 'חזרה לתפריט',
    leaderboard: 'טבלת המובילים',
    rank: 'מקום {n} בקבוצת הגיל!',
    newBest: 'שיא אישי חדש!',
  },
  leaderboard: {
    title: 'טבלת המובילים',
    subtitle: 'כל קבוצת גיל מתחרה בנפרד',
    columns: {
      rank: 'מקום',
      nickname: 'כינוי',
      score: 'ניקוד',
      correct: 'נכונות',
      time: 'זמן',
      livesLost: 'חיים שאבדו',
      date: 'תאריך',
    },
    empty: { m: 'עדיין אין תוצאות בקבוצת הגיל הזו. היה הראשון!', f: 'עדיין אין תוצאות בקבוצת הגיל הזו. היי הראשונה!' } as G,
    unavailable: 'טבלת המובילים אינה זמינה כרגע.',
    localNote: 'התוצאות נשמרות במכשיר הזה',
    onlineNote: 'טבלה מקוונת',
    retry: 'ניסיון חוזר',
    you: 'את/ה',
  },
  settings: {
    title: 'הגדרות',
    audio: 'שמע',
    master: 'עוצמת שמע',
    music: 'מוזיקה',
    sfx: 'אפקטים',
    mute: 'השתקה',
    graphics: 'גרפיקה',
    quality: { auto: 'אוטומטי', low: 'נמוך', medium: 'בינוני', high: 'גבוה', ultra: 'אולטרה' } satisfies Record<QualitySetting, string>,
    controls: 'שליטה',
    mouseSensitivity: 'רגישות עכבר',
    touchSensitivity: 'רגישות מגע',
    accessibility: 'נגישות',
    reducedMotion: 'הפחתת תנועה',
    reducedMotionHint: 'מבטל נדנוד מצלמה, רעידות ותנועות קולנועיות',
    showMinimap: 'מפה קסומה בפינת המסך',
    address: 'פנייה',
    resetTutorial: 'הצג הדרכה מחדש',
    tutorialReset: 'ההדרכה תוצג במשחק הבא',
    on: 'פועל',
    off: 'כבוי',
  },
  resume: {
    title: 'המשחק הקודם עדיין ממתין לך. להמשיך?',
    details: '{theme} · גילאי {age} · {time} נותרו · {lives} חיים',
    continue: 'המשך משחק',
    newGame: 'משחק חדש',
  },
  orientation: { m: 'לחוויה הטובה ביותר, סובב את המכשיר לרוחב', f: 'לחוויה הטובה ביותר, סובבי את המכשיר לרוחב' } as G,
  errors: {
    noWebgl: 'הדפדפן הזה אינו תומך בגרפיקה תלת־ממדית. נסו דפדפן עדכני אחר.',
    generic: 'משהו השתבש. נסו לרענן את הדף.',
    offline: 'אין חיבור לרשת — המשחק ממשיך כרגיל.',
  },
  time: {
    format: '{m}:{s}',
  },
} as const;

export const TREASURE_NAMES = ['גביש קסום', 'מטבע עתיק', 'שבר רונה', 'נוצה זוהרת', 'מגילה עתיקה', 'קמע כסוף'] as const;

export const LOADING_TIPS: G[] = [
  { m: 'יצור שעזרת לו בתשובה נכונה ידליק לך את הדרך.', f: 'יצור שעזרת לו בתשובה נכונה ידליק לך את הדרך.' },
  'גם אחרי תשובה שגויה — כל הדרכים פתוחות. המבוך לא נועל אותך.',
  'אוצרות נשמרים רק כשמגיעים לנקודת ביקורת.',
  'המפה הקסומה מציירת רק את מה שכבר ראית.',
  { m: 'מבוי סתום? לפעמים מסתתר בו אוצר — או מישהו שמחכה לך.', f: 'מבוי סתום? לפעמים מסתתר בו אוצר — או מישהו שמחכה לך.' },
  'כל עשר דקות המבוך דורש מחיר: חיים אחד.',
  'דרך יעילה מוסיפה בונוס בסוף המסע.',
];

export const AUDIO_CAPTIONS = {
  roar: '[שאגה רחוקה מהדהדת במבוך]',
  wings: '[משק כנפיים עצום מעליך]',
  whisper: '[לחישות עמומות מעבר לקיר]',
  rumble: '[האדמה רועדת קלות]',
  chime: '[צלצול גבישי רחוק]',
  door: '[דלת אבן כבדה נסגרת אי שם]',
} as const;
