import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--use-angle=d3d11', '--enable-gpu', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') errors.push(m.text()); });
await page.goto('http://localhost:5299/');
await page.waitForTimeout(5000);
console.log('devApi exposed:', await page.evaluate(() => typeof window.__tm));
await page.getByRole('button', { name: 'התחל משחק' }).click();
await page.locator('.age-card').nth(3).click();
await page.getByRole('button', { name: 'דילוג על ההדרכה' }).click();
await page.waitForSelector('.hud', { timeout: 180000 });
await page.waitForTimeout(3000);
await page.keyboard.down('KeyW'); await page.waitForTimeout(1500); await page.keyboard.up('KeyW');
await page.screenshot({ path: 'scripts/screenshots/out/prod-playing.png' });
console.log('hud visible:', await page.locator('.hud-clock').innerText());
console.log('errors:', errors.length ? errors : 'none');
await browser.close();
