import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--use-angle=d3d11', '--enable-gpu', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const wait = (ms) => page.waitForTimeout(ms);
const phase = () => page.evaluate(() => window.__tm?.state().phase);
const theme = process.env.THEME ?? 'forest';
await page.goto(`http://localhost:5199/?theme=${theme}&seed=77`);
await page.evaluate(() => { localStorage.clear(); localStorage.setItem('tm.settings.v1', JSON.stringify({ tutorialSeen: true })); });
await page.reload();
await wait(2500);
await page.getByRole('button', { name: 'התחל משחק' }).click();
await page.locator('.age-card').nth(2).click();
await page.getByRole('button', { name: /היכנס למבוך/ }).click();
while ((await phase()) !== 'PLAYING') await wait(250);
await page.evaluate(() => {
  const r = window.__tm.controller.run;
  const sol = r.maze.solution;
  const prev = r.world.cellCenter(sol[sol.length - 2]);
  const ex = r.world.exit.position;
  r.player.teleport(prev.x, prev.z, Math.atan2(-(ex.x - prev.x), -(ex.z - prev.z)));
});
await wait(3000);
await page.screenshot({ path: `scripts/screenshots/out/exit-${theme}.png` });
await page.keyboard.down('KeyW');
for (let i = 0; i < 60 && (await phase()) !== 'VICTORY'; i++) await wait(150);
await page.keyboard.up('KeyW');
while ((await phase()) !== 'SCORE_SUMMARY') await wait(250);
await wait(1500);
await page.screenshot({ path: `scripts/screenshots/out/victory-summary-${theme}.png` });
console.log('done');
await browser.close();
